version: '3.8'
services:
  nacos:
    image: nacos/nacos-server:v2.3.1-slim
    container_name: nacos-standalone
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    restart: always
