export const QUESTION_REVIEW_STATUS_ENUM = {
  PENDING: 0,
  APPROVED: 1,
  REJECTED: 2,
} as const;

export const QUESTION_REVIEW_STATUS_TEXT_MAP: Record<number, string> = {
  [QUESTION_REVIEW_STATUS_ENUM.PENDING]: "待审核",
  [QUESTION_REVIEW_STATUS_ENUM.APPROVED]: "已通过",
  [QUESTION_REVIEW_STATUS_ENUM.REJECTED]: "已驳回",
};

export const QUESTION_REVIEW_STATUS_COLOR_MAP: Record<number, string> = {
  [QUESTION_REVIEW_STATUS_ENUM.PENDING]: "gold",
  [QUESTION_REVIEW_STATUS_ENUM.APPROVED]: "green",
  [QUESTION_REVIEW_STATUS_ENUM.REJECTED]: "red",
};

export const QUESTION_REVIEW_STATUS_OPTIONS = [
  { label: "待审核", value: QUESTION_REVIEW_STATUS_ENUM.PENDING },
  { label: "已通过", value: QUESTION_REVIEW_STATUS_ENUM.APPROVED },
  { label: "已驳回", value: QUESTION_REVIEW_STATUS_ENUM.REJECTED },
];

export const QUESTION_REVIEW_STATUS_VALUE_ENUM = {
  [QUESTION_REVIEW_STATUS_ENUM.PENDING]: { text: "待审核" },
  [QUESTION_REVIEW_STATUS_ENUM.APPROVED]: { text: "已通过" },
  [QUESTION_REVIEW_STATUS_ENUM.REJECTED]: { text: "已驳回" },
};
